### ISSUE TITLE
Hash changes even if password doesn't

### ISSUE THREAD

**Issue by ekristen** [loafoe/terraform-provider-htpasswd#1]
First, thanks for the module.

Second, it looks like the hash is re-computed every time even if the password doesn't change (ie `apr1`). This shouldn't be recalculated every time especially when resources are depending on it.

It would appear that https://github.com/loafoe/terraform-provider-htpasswd/blob/main/htpasswd/data_source_password.go#L42 would keep that from happening, but it's definitely not. The resource isn't new and the password is not changing, yet it is still making it into the block and re-generating the hash.

**Comment by ekristen** [comment]
This is actual an issue if you leave the salt blank. The salt should be stored.

**Comment by ekristen** [comment]
This might be related to https://github.com/hashicorp/terraform-plugin-sdk/issues/98, keeping the salt the same doesnt fix it either, regardless in terraform 14, it always generates a new hash.

**Comment by loafoe** [comment]
This worked for me during initial development:

```hcl
resource "random_password" "password" {
  length = 30
}

data "htpasswd_password" "hash" {
  password = random_password.password.result
  salt     = substr(sha512(random_password.password.result), 0, 8)
}
```

I'll test it with the latest version of Terraform..

**Comment by loafoe** [comment]
@ekristen tested above with latest terraform and it produces stable state. I've modified the example in the documentation to include the `salt` attribute. Can you confirm it works for you?
