### ISSUE TITLE
Using password as salt is poor security practice

### ISSUE THREAD

**Issue by MarcClusterman** [loafoe/terraform-provider-htpasswd#17]
The example for htpassword hashing provide the following guidance:

```
resource "htpasswd_password" "hash" {
  password = random_password.password.result
  salt     = substr(sha512(random_password.password.result), 0, 8)
}
```

This means that a given password will always generate the same hash value, which arguably defeats the purpose of having a salt in the first place. I would suggest using a different `random_string` to generate the salt rather than the password itself.

**Comment by loafoe** [comment]
@MarcClusterman thanks for the feedback! The example is updated in the latest release `v1.0.3`
