### ISSUE TITLE
Support bcrypt as a modern algorithm

### ISSUE THREAD

**Issue by moritzheiber** [loafoe/terraform-provider-htpasswd#3]
Love this provider, thank you for your work!

I'd like to see `bcrypt` implemented as a hashing algorithm, if possible (at least the original Go module [would suggest it is supported](https://github.com/johnaoss/htpasswd/blob/master/hashing.go#L35-L41)). Some of the more modern `htpasswd` applications (case and point: Docker Distribution) require algos like `bcrypt` instead of the weaker ones like `md5` or `sha1`.

Thanks!

**Comment by loafoe** [comment]
Will definitely look into adding it. BTW `bcrypt` is [available as a method](https://www.terraform.io/docs/language/functions/bcrypt.html) in Terraform core so you might use that for the time being?

**Comment by moritzheiber** [comment]
Totally, yes, but unfortunately (as the documentation notes) it produces "spurious" diffs (meaning, the value changes with each apply, although the underlying password will not change) due to the nature of `bcrypt`'s hashing algorithm, i.e. it'll be a little noisy and potentially require re-provisioning of resources that haven't actually changed. I trust in this provider to basically be a remedy for that problem :slightly_smiling_face:

**Comment by loafoe** [comment]
Haha, if bcrypt has a seed that can be controlled, sure. This is how the provider currently gets around preventing spurious diffs for apr1. I'll have a look shortly.

**Comment by loafoe** [comment]
Allright, I figured out a way to support this, but this will introduce a very hard breaking change, namely that the data source will become a resource 😆 

I will do some testing and bump the provider to the `1.0.0` release to signal breakage

**Comment by loafoe** [comment]
@moritzheiber please try the `v0.9.0` release which includes bcrypt support! Note that you'll have to switch from the data source element to the `resource` one to get bcrypt.

**Comment by moritzheiber** [comment]
@loafoe Can confirm that this does both, add `bcrypt` as an algorithm _and_ avoid spurious diffs during `apply` runs. Fantastic work, thank you! :heart: :tada:
